# Site settings
title: Spring Staycations
client:
  name: Flybe
  link: https://www.flybe.com/?utm_medium=display&utm_source=secret_escapes&utm_campaign=fy20216_secret_escapes&utm_content=microsite_logo
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Rediscover Britain with our pick of spring staycations. Start your travel season early with a quick and easy getaway, flying with Flybe to a variety of destinations. From the down to earth atmosphere of Glasgow to the wild charms of Jersey, give yourself the chance to escape this spring. Where will Flybe take you?

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/flybe" # the subpath of the site, including territory and year
img:     "/uk/2020/flybe/_assets/img"
css:     "/uk/2020/flybe/_assets/css"
js:      "/uk/2020/flybe/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed